cloud:
  aws:
    credentials:
      accessKey:      # AWS IAM AccessKey 적기
      secretKey:   # AWS IAM SecretKey 적기
    s3:
      bucket:    # ex) marryting-gyunny
      dir:  # ex) /gyunny
    region:
      static: 
    stack:
      auto:
