cloud:
  aws:
    credentials:
      accessKey: AKIA5DHNFTCOFQA4RVWR       # AWS IAM AccessKey 적기
      secretKey: q4AhEH7w/GE/pb31ssxVOQpYke23iCcCNkEp/Pjk   # AWS IAM SecretKey 적기
    s3:
      bucket: board-team10    # ex) marryting-gyunny
      dir: post # ex) /gyunny
    region:
      static: ap-northeast-2
    stack:
      auto: false