###회원가입1############
POST http://localhost:8080/api/member/signup
Content-Type: application/json

{
  "nickname":"kiyeon",
  "password":"1234",
  "passwordConfirm":"1234"
}

###회원가입2############
POST http://localhost:8080/api/member/signup
Content-Type: application/json

{
  "nickname":"seonghee",
  "password":"1234",
  "passwordConfirm":"1234"
}


###로그인1##################
POST http://15.164.163.50:8090/api/member/login
Content-Type: application/json

{
  "nickname":"kiyeon",
  "password":"1234"
}

###로그인2##################
POST http://localhost:8080/api/member/login
Content-Type: application/json

{
  "nickname":"seonghee",
  "password":"1234"
}

###멤버1 게시글 작성##############

POST http://localhost:8080/api/auth/post
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjIwNDI0NDh9.1dCV0KlpQeu1Rfs3Th3KW9oECotfd4A-q1WykY7u25I
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2NDM2NDh9.kfVrvUdEAZlWa4VEys9-6DVRZWNqD1X50EGg-IYkafI
Content-Type: application/json

{
  "title":"게시글 test1",
  "content":"회원1의 게시글 내용 1"
}

###멤버1 게시글 작성##############

POST http://localhost:8080/api/auth/post
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjIwNDI0NDh9.1dCV0KlpQeu1Rfs3Th3KW9oECotfd4A-q1WykY7u25I
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2NDM2NDh9.kfVrvUdEAZlWa4VEys9-6DVRZWNqD1X50EGg-IYkafI
Content-Type: application/json

{
  "title":"게시글 test2",
  "content":"회원1의 게시글 내용 2"
}

###게시글 확인###########
GET http://localhost:8080/api/post



###멤버1 댓글 달기##############

POST http://localhost:8080/api/auth/comment
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjIwNTEwODZ9.NxegFxu6UVPxlkbltYCaPxB0vuOWnnwaXR1pSdIK8ck
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2NTIyODZ9.KyZCbTBavzKyKJ6hsAk4qEGXnOgb4fUx16m6f_2DKts
Content-Type: application/json

{
  "postId":"1",
  "content":"댓글 작성자: 회원1/ 게시글 1의 댓글 1"

}



###댓글 확인##################
GET http://localhost:8080/api/comment/1

###멤버2 댓글 달기##############

POST http://localhost:8080/api/auth/comment
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjA1MTEwOX0.NZLCz8B70Ptle-ZGjAl_lt_GZTPB04sS78iyRx5-RQY
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2NTIzMDl9.ANgZ3UbaXdPB-6x3xbCk8yBXvx2wG-JfBhQDuzvjZhA
Content-Type: application/json

{
  "postId":"2",
  "content":"댓글 작성자: 회원2/ 게시글 2의 댓글 2"

}

####회원 1의 자기 댓글 업데이트##############
PUT http://localhost:8080/api/auth/comment/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjIwNTEwODZ9.NxegFxu6UVPxlkbltYCaPxB0vuOWnnwaXR1pSdIK8ck
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2NTIyODZ9.KyZCbTBavzKyKJ6hsAk4qEGXnOgb4fUx16m6f_2DKts
Content-Type: application/json

{
  "postId":"2",
  "content":"댓글 수정자: 회원2/ 게시글 2의 댓글 1의 본인 수정버전"
}


###멤버2 댓글 달기##############

POST http://localhost:8080/api/auth/comment
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjA1MTEwOX0.NZLCz8B70Ptle-ZGjAl_lt_GZTPB04sS78iyRx5-RQY
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2NTIzMDl9.ANgZ3UbaXdPB-6x3xbCk8yBXvx2wG-JfBhQDuzvjZhA
Content-Type: application/json

{
  "postId":"2",
  "content":"댓글 작성자: 회원2/ 게시글 2의 댓글3"

}


###회원1 대댓글 달기1#################
POST http://localhost:8080/api/auth/recomment
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjIwNTEwODZ9.NxegFxu6UVPxlkbltYCaPxB0vuOWnnwaXR1pSdIK8ck
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2NTIyODZ9.KyZCbTBavzKyKJ6hsAk4qEGXnOgb4fUx16m6f_2DKts
Content-Type: application/json

{
  "postId":"1",
  "commentId":"1",
  "content":"대댓글 작성자: 회원1/ 게시글 1의 댓글 1의 대댓글 1"
}

###회원2 대댓글 달기2#################
POST http://localhost:8080/api/auth/recomment
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjA1MTEwOX0.NZLCz8B70Ptle-ZGjAl_lt_GZTPB04sS78iyRx5-RQY
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2NTIzMDl9.ANgZ3UbaXdPB-6x3xbCk8yBXvx2wG-JfBhQDuzvjZhA
Content-Type: application/json

{
  "postId":"2",
  "commentId":"1",
  "content":"대댓글 작성자: 회원2/ 게시글 1의 댓글 1의 대댓글 2"
}


###댓글1의 대댓글 확인#################
GET http://localhost:8080/api/recomment/1


####회원2 대댓글 수정 확인#############
PUT http://localhost:8080/api/auth/recomment/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjA1MTEwOX0.NZLCz8B70Ptle-ZGjAl_lt_GZTPB04sS78iyRx5-RQY
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2NTIzMDl9.ANgZ3UbaXdPB-6x3xbCk8yBXvx2wG-JfBhQDuzvjZhA
Content-Type: application/json

{

  "postId":"2",
  "commentId":"1",
  "content":"대댓글 수정자: 회원2/ 게시글 2의 댓글 1의 대댓글 2의 수정"

}

#### 회원1 post1에 좋아요
POST http://localhost:8080/api/auth/like/post/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjIwNTEwODZ9.NxegFxu6UVPxlkbltYCaPxB0vuOWnnwaXR1pSdIK8ck
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2NTIyODZ9.KyZCbTBavzKyKJ6hsAk4qEGXnOgb4fUx16m6f_2DKts

##### 회원2 post2에 좋아요
POST http://localhost:8080/api/auth/like/post/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjA1MTEwOX0.NZLCz8B70Ptle-ZGjAl_lt_GZTPB04sS78iyRx5-RQY
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2NTIzMDl9.ANgZ3UbaXdPB-6x3xbCk8yBXvx2wG-JfBhQDuzvjZhA

#### 회원1 post1에 좋아요 취소
POST http://localhost:8080/api/auth/like/post/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjIwNTEwODZ9.NxegFxu6UVPxlkbltYCaPxB0vuOWnnwaXR1pSdIK8ck
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2NTIyODZ9.KyZCbTBavzKyKJ6hsAk4qEGXnOgb4fUx16m6f_2DKts



###  회원1 댓글2에 좋아요
POST http://localhost:8080/api/auth/like/comment/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjIwNTEwODZ9.NxegFxu6UVPxlkbltYCaPxB0vuOWnnwaXR1pSdIK8ck
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2NTIyODZ9.KyZCbTBavzKyKJ6hsAk4qEGXnOgb4fUx16m6f_2DKts


### 회원2 댓글 2에 좋아요
POST http://localhost:8080/api/auth/like/comment/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjA1MTEwOX0.NZLCz8B70Ptle-ZGjAl_lt_GZTPB04sS78iyRx5-RQY
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2NTIzMDl9.ANgZ3UbaXdPB-6x3xbCk8yBXvx2wG-JfBhQDuzvjZhA

#### 회원2 댓글 2에 좋아요 취소
POST http://localhost:8080/api/auth/like/comment/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjA1MTEwOX0.NZLCz8B70Ptle-ZGjAl_lt_GZTPB04sS78iyRx5-RQY
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2NTIzMDl9.ANgZ3UbaXdPB-6x3xbCk8yBXvx2wG-JfBhQDuzvjZhA

#### 회원2 대댓글1에 좋아요
POST http://localhost:8080/api/auth/like/recomment/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjA1MTEwOX0.NZLCz8B70Ptle-ZGjAl_lt_GZTPB04sS78iyRx5-RQY
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2NTIzMDl9.ANgZ3UbaXdPB-6x3xbCk8yBXvx2wG-JfBhQDuzvjZhA

#### 회원2 대댓글1에 좋아요 취소
POST http://localhost:8080/api/auth/like/recomment/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjA1MTEwOX0.NZLCz8B70Ptle-ZGjAl_lt_GZTPB04sS78iyRx5-RQY
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2NTIzMDl9.ANgZ3UbaXdPB-6x3xbCk8yBXvx2wG-JfBhQDuzvjZhA

##### 회원2 대댓글2에 좋아요
POST http://localhost:8080/api/auth/like/recomment/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjA1NDI4NX0.eT5B7SYZ3xnkjzoRQvtMfp26D39EHWeZpGdA0bOcKvM
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2NTU0ODV9.dx37ejxHpKbWtGSDXdte7WUDUzuQyKFRe37uClZF9HA
#
#### 회원2 대댓글2에 좋아요
#POST http://localhost:8080/api/auth/like/recomment/2
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjAxOTk2OH0.5ISIF9uRpvCrid65F-fgF0RWPGolQrmP83vPJH3Rdxo
#Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2MjExNjh9.14P5uuem9Onr0e1jdA7KloCpaIhtaPO1sxUk3t6zeA8

### 회원1


######## 회원1 작성한 게시글, 댓글, 대댓글 마이페이지
GET http://localhost:8080/api/auth/member/mypage/writes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjIwNTEwODZ9.NxegFxu6UVPxlkbltYCaPxB0vuOWnnwaXR1pSdIK8ck
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2NTIyODZ9.KyZCbTBavzKyKJ6hsAk4qEGXnOgb4fUx16m6f_2DKts


######## 회원2 작성한 게시글, 댓글, 대댓글 마이페이지
GET http://localhost:8080/api/auth/member/mypage/writes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjAxOTk2OH0.5ISIF9uRpvCrid65F-fgF0RWPGolQrmP83vPJH3Rdxo
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2MjExNjh9.14P5uuem9Onr0e1jdA7KloCpaIhtaPO1sxUk3t6zeA8

######## 회원1 좋아요한 게시글, 댓글, 대댓글 마이페이지
GET http://localhost:8080/api/auth/member/mypage/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjIwNTEwODZ9.NxegFxu6UVPxlkbltYCaPxB0vuOWnnwaXR1pSdIK8ck
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2NTIyODZ9.KyZCbTBavzKyKJ6hsAk4qEGXnOgb4fUx16m6f_2DKts


######## 회원2 좋아요한 게시글, 댓글, 대댓글 마이페이지
GET http://localhost:8080/api/auth/member/mypage/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjA0MzYwMn0.1NKqZLWbpLewSmiOOR4p1_tu9YPN7q0AphMv3deabms
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2NDQ4MDJ9.fuzYv0lYSJLBoFpkRMspB22V-vxTp3cXPD2FtIN3Uis

##########삭제 ###############

###대댓글 2번 삭제 확인#############
DELETE http://localhost:8080/api/auth/recomment/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjA1MTEwOX0.NZLCz8B70Ptle-ZGjAl_lt_GZTPB04sS78iyRx5-RQY
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2NTIzMDl9.ANgZ3UbaXdPB-6x3xbCk8yBXvx2wG-JfBhQDuzvjZhA

#####회원2 댓글2에 대댓글 달기
POST http://localhost:8080/api/auth/recomment
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjA1MTEwOX0.NZLCz8B70Ptle-ZGjAl_lt_GZTPB04sS78iyRx5-RQY
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2NTIzMDl9.ANgZ3UbaXdPB-6x3xbCk8yBXvx2wG-JfBhQDuzvjZhA
Content-Type: application/json

{
  "postId":"2",
  "commentId":"2",
  "content":"대댓글입니다"
}

### 회원2 대댓글3에 좋아요
POST http://localhost:8080/api/auth/like/recomment/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjA1MTEwOX0.NZLCz8B70Ptle-ZGjAl_lt_GZTPB04sS78iyRx5-RQY
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2NTIzMDl9.ANgZ3UbaXdPB-6x3xbCk8yBXvx2wG-JfBhQDuzvjZhA


####회원2 댓글 2번 삭제 확인
DELETE http://localhost:8080/api/auth/comment/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjA1MTEwOX0.NZLCz8B70Ptle-ZGjAl_lt_GZTPB04sS78iyRx5-RQY
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2NTIzMDl9.ANgZ3UbaXdPB-6x3xbCk8yBXvx2wG-JfBhQDuzvjZhA

#####post2 삭제
DELETE http://localhost:8080/api/auth/post/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjIwNTQ0Mzd9.VMgh8SB8_M_m8bGzeZMee9QWM0ODwC8otMUUxlJfODI
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2NTU2Mzd9.Gg2KFNdSoqe-yMxpj4xRRECALtMd3HBNr5WEH61_y1U