###회원가입1############
POST http://localhost:8080/api/member/signup
Content-Type: application/json

{
  "nickname":"kiyeon",
  "password":"1234",
  "passwordConfirm":"1234"
}

###회원가입2############
POST http://localhost:8080/api/member/signup
Content-Type: application/json

{
  "nickname":"seonghee",
  "password":"1234",
  "passwordConfirm":"1234"
}


###로그인1##################
POST http://localhost:8080/api/member/login
Content-Type: application/json

{
  "nickname":"kiyeon",
  "password":"1234"
}

###로그인2##################
POST http://localhost:8080/api/member/login
Content-Type: application/json

{
  "nickname":"seonghee",
  "password":"1234"
}

###멤버1 게시글 작성##############

POST http://localhost:8080/api/auth/post
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjIwMTMzOTd9.WJX3rEFFgvjA6WNu1alCJyQ_78uzklG7h-x-iAzPLjk
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2MTYzOTd9.-8vZb9S-ZKcDyqGSwjUHO_6OhVLPgUpMjrWd5BKVTQA
Content-Type: application/json

{
  "title":"게시글 test1",
  "content":"회원1의 게시글 내용 1"
}

###멤버1 게시글 작성##############

POST http://localhost:8080/api/auth/post
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjIwMDg2OTF9.Wo7xClq4Cmd8pG2AEljIJFex-5WWFyrPaFMdmEVWcc8
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2MTE2OTF9.y1op-3G4OMLkKlGOcdoCK29OecPZSJ473kBNCZzTDDg
Content-Type: application/json

{
  "title":"게시글 test2",
  "content":"회원1의 게시글 내용 1"
}

###게시글 확인###########
GET http://localhost:8090/api/post/4



###멤버1 댓글 달기##############

POST http://localhost:8080/api/auth/comment
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjIwMTMzOTd9.WJX3rEFFgvjA6WNu1alCJyQ_78uzklG7h-x-iAzPLjk
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2MTYzOTd9.-8vZb9S-ZKcDyqGSwjUHO_6OhVLPgUpMjrWd5BKVTQA
Content-Type: application/json

{
"postId":"1",
"content":"댓글 작성자: 회원1/ 게시글 1의 댓글 1"

}

###댓글 확인##################
GET http://localhost:8080/api/comment/1

###멤버2 댓글 달기##############

POST http://localhost:8080/api/auth/comment
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjAxMjc4OH0.-TST4tZT2HaeHJ1mia7BIeToQeNGZ8xCgOc6OEkq-K8
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2MTU3ODh9.zEWWY2E98xzhKxSVCNcZh-BLCa0CKxyQx6-SzQndN1M
Content-Type: application/json

{
  "postId":"2",
  "content":"댓글 작성자: 회원2/ 게시글 2의 댓글 1"

}

####회원 1의 자기 댓글 업데이트##############
PUT http://localhost:8080/api/auth/comment/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjAxMjc4OH0.-TST4tZT2HaeHJ1mia7BIeToQeNGZ8xCgOc6OEkq-K8
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2MTU3ODh9.zEWWY2E98xzhKxSVCNcZh-BLCa0CKxyQx6-SzQndN1M
Content-Type: application/json

{
  "postId":"2",
  "content":"댓글 수정자: 회원2/ 게시글 2의 댓글 1의 본인 수정버전"
}


###멤버2 댓글 달기##############

POST http://localhost:8080/api/auth/comment
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjAxOTk2OH0.5ISIF9uRpvCrid65F-fgF0RWPGolQrmP83vPJH3Rdxo
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2MjExNjh9.14P5uuem9Onr0e1jdA7KloCpaIhtaPO1sxUk3t6zeA8
Content-Type: application/json

{
  "postId":"4",
  "content":"댓글 작성자: 회원2/ 게시글 3의 댓글 4"

}


###회원1 대댓글 달기1#################
POST http://localhost:8080/api/auth/recomment
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjIwMTMzOTd9.WJX3rEFFgvjA6WNu1alCJyQ_78uzklG7h-x-iAzPLjk
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2MTYzOTd9.-8vZb9S-ZKcDyqGSwjUHO_6OhVLPgUpMjrWd5BKVTQA
Content-Type: application/json

{
  "postId":"1",
  "commentId":"1",
  "content":"대댓글 작성자: 회원1/ 게시글 1의 댓글 1의 대댓글 1"
}

###회원2 대댓글 달기2#################
POST http://localhost:8080/api/auth/recomment
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjAxMjc4OH0.-TST4tZT2HaeHJ1mia7BIeToQeNGZ8xCgOc6OEkq-K8
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2MTU3ODh9.zEWWY2E98xzhKxSVCNcZh-BLCa0CKxyQx6-SzQndN1M
Content-Type: application/json

{
  "postId":"2",
  "commentId":"1",
  "content":"대댓글 작성자: 회원2/ 게시글 1의 댓글 1의 대댓글 2"
}

###회원2 대댓글 달기2#################
POST http://localhost:8080/api/auth/recomment
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjAxOTk2OH0.5ISIF9uRpvCrid65F-fgF0RWPGolQrmP83vPJH3Rdxo
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2MjExNjh9.14P5uuem9Onr0e1jdA7KloCpaIhtaPO1sxUk3t6zeA8
Content-Type: application/json

{
  "postId":"4",
  "commentId":"4",
  "content":"대댓글 작성자: 회원2/ 게시글 4의 댓글 4의 대댓글 "
}

###댓글1의 대댓글 확인#################
GET http://localhost:8080/api/recomment/1


####대댓글 수정 확인#############
#PUT http://localhost:8080/api/auth/recomment/1
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MTg2NjU3OX0.e3pd6uGMQozEw0y2Ed3jzEhdMjpLIJ8norsaBtb8Zdo
#Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI0Njk1Nzl9.gmFYKEu_cmPZKIjNLZq3MmKM3DYk_9_3_IMEZcMoDHY
#Content-Type: application/json
#
#{
#
#  "postId":"1",
#  "commentId":"2",
#  "content":"대댓글 수정자: 회원2/ 게시글 1의 댓글 1의 대댓글 1의 수정"
#
#}

#### 회원1 post1에 좋아요
POST http://localhost:8080/api/auth/like/post/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjIwMTk5NTZ9.QVB0OfuTYI47p2KnlU1YN0tNbWe5s3fMMZ-A683oXTY
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2MjExNTZ9.2WjUKff4vPRDcOA63Nf4eT9ak6jGgY310hWd7ZwDgCY

##### 회원2 post3에 좋아요
POST http://localhost:8080/api/auth/like/post/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjAxOTk2OH0.5ISIF9uRpvCrid65F-fgF0RWPGolQrmP83vPJH3Rdxo
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2MjExNjh9.14P5uuem9Onr0e1jdA7KloCpaIhtaPO1sxUk3t6zeA8

#### 회원1 post3에 좋아요 취소
POST http://localhost:8080/api/auth/like/post/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjIwMTk5NTZ9.QVB0OfuTYI47p2KnlU1YN0tNbWe5s3fMMZ-A683oXTY
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2MjExNTZ9.2WjUKff4vPRDcOA63Nf4eT9ak6jGgY310hWd7ZwDgCY

##### 회원1 post2에 좋아요 취소
#POST http://localhost:8080/api/auth/like/post/2
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjIwMTk5NTZ9.QVB0OfuTYI47p2KnlU1YN0tNbWe5s3fMMZ-A683oXTY
#Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2MjExNTZ9.2WjUKff4vPRDcOA63Nf4eT9ak6jGgY310hWd7ZwDgCY

###  회원1 댓글3에 좋아요
POST http://localhost:8080/api/auth/like/comment/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjIwMTk5NTZ9.QVB0OfuTYI47p2KnlU1YN0tNbWe5s3fMMZ-A683oXTY
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2MjExNTZ9.2WjUKff4vPRDcOA63Nf4eT9ak6jGgY310hWd7ZwDgCY

#### 회원1 댓글4에 좋아요
POST http://localhost:8080/api/auth/like/comment/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjIwMTk5NTZ9.QVB0OfuTYI47p2KnlU1YN0tNbWe5s3fMMZ-A683oXTY
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2MjExNTZ9.2WjUKff4vPRDcOA63Nf4eT9ak6jGgY310hWd7ZwDgCY

### 회원2 댓글 3에 좋아요
POST http://localhost:8080/api/auth/like/comment/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjAxOTk2OH0.5ISIF9uRpvCrid65F-fgF0RWPGolQrmP83vPJH3Rdxo
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2MjExNjh9.14P5uuem9Onr0e1jdA7KloCpaIhtaPO1sxUk3t6zeA8

#### 회원2 댓글 3에 좋아요 취소
POST http://localhost:8080/api/auth/like/comment/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjAxOTk2OH0.5ISIF9uRpvCrid65F-fgF0RWPGolQrmP83vPJH3Rdxo
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2MjExNjh9.14P5uuem9Onr0e1jdA7KloCpaIhtaPO1sxUk3t6zeA8

#### 회원2 대댓글3에 좋아요
POST http://localhost:8080/api/auth/like/recomment/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjAxOTk2OH0.5ISIF9uRpvCrid65F-fgF0RWPGolQrmP83vPJH3Rdxo
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2MjExNjh9.14P5uuem9Onr0e1jdA7KloCpaIhtaPO1sxUk3t6zeA8

#### 회원2 대댓글3에 좋아요 취소
POST http://localhost:8080/api/auth/like/recomment/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjAxOTk2OH0.5ISIF9uRpvCrid65F-fgF0RWPGolQrmP83vPJH3Rdxo
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2MjExNjh9.14P5uuem9Onr0e1jdA7KloCpaIhtaPO1sxUk3t6zeA8

##### 회원2 대댓글2에 좋아요 취소
#POST http://localhost:8080/api/auth/like/recomment/2
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjAxOTk2OH0.5ISIF9uRpvCrid65F-fgF0RWPGolQrmP83vPJH3Rdxo
#Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2MjExNjh9.14P5uuem9Onr0e1jdA7KloCpaIhtaPO1sxUk3t6zeA8
#
#### 회원2 대댓글2에 좋아요
#POST http://localhost:8080/api/auth/like/recomment/2
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjAxOTk2OH0.5ISIF9uRpvCrid65F-fgF0RWPGolQrmP83vPJH3Rdxo
#Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2MjExNjh9.14P5uuem9Onr0e1jdA7KloCpaIhtaPO1sxUk3t6zeA8

### 회원1


###대댓글 2번 삭제 확인#############
DELETE http://localhost:8080/api/auth/recomment/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjAxMjc4OH0.-TST4tZT2HaeHJ1mia7BIeToQeNGZ8xCgOc6OEkq-K8
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2MTU3ODh9.zEWWY2E98xzhKxSVCNcZh-BLCa0CKxyQx6-SzQndN1M

######## 회원1 작성한 게시글, 댓글, 대댓글 마이페이지
GET http://localhost:8080/api/auth/member/mypage/writes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjIwMTk5NTZ9.QVB0OfuTYI47p2KnlU1YN0tNbWe5s3fMMZ-A683oXTY
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2MjExNTZ9.2WjUKff4vPRDcOA63Nf4eT9ak6jGgY310hWd7ZwDgCY


######## 회원2 작성한 게시글, 댓글, 대댓글 마이페이지
GET http://localhost:8080/api/auth/member/mypage/writes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjAxOTk2OH0.5ISIF9uRpvCrid65F-fgF0RWPGolQrmP83vPJH3Rdxo
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2MjExNjh9.14P5uuem9Onr0e1jdA7KloCpaIhtaPO1sxUk3t6zeA8

######## 회원1 좋아요한 게시글, 댓글, 대댓글 마이페이지
GET http://localhost:8080/api/auth/member/mypage/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJleHAiOjE2NjIwMTk5NTZ9.QVB0OfuTYI47p2KnlU1YN0tNbWe5s3fMMZ-A683oXTY
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2MjExNTZ9.2WjUKff4vPRDcOA63Nf4eT9ak6jGgY310hWd7ZwDgCY


######## 회원2 좋아요한 게시글, 댓글, 대댓글 마이페이지
GET http://localhost:8080/api/auth/member/mypage/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZW9uZ2hlZSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MjAxOTk2OH0.5ISIF9uRpvCrid65F-fgF0RWPGolQrmP83vPJH3Rdxo
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjI2MjExNjh9.14P5uuem9Onr0e1jdA7KloCpaIhtaPO1sxUk3t6zeA8
